version: "3.7"
services:
  blogapitesting:
    build:
      context: .
      dockerfile: test.Dockerfile
    depends_on:
      - postgresdb
    environment:
      - POSTGRES_HOST=postgresdb
  postgresdb:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=abc123
    restart: always
